use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "change-this-to-any-random-32-chars-long-string-now"

search:
  formats:
    - html
    - json

outgoing:
  proxies:
    all://:
      - http://iitlibye:3cr6n3ulhiku@31.59.20.176:6754
      - http://iitlibye:3cr6n3ulhiku@45.38.107.97:6014
      - http://iitlibye:3cr6n3ulhiku@64.137.96.74:6641
      - http://iitlibye:3cr6n3ulhiku@198.23.243.226:6361